### ISSUE TITLE
现在不能用了

### ISSUE THREAD

**Issue by jiancheng2018** [wakasann/gksvideourla#3]
是不是把他删掉了？

**Comment by wakasann** [comment]
抱歉，发布的旧版本是不能用了，你如果有环境的话，可以使用目前的源码在android studio编译的一个apk出来，因为我电脑还原了系统，我目前暂时没有环境进行编译一个新的apk, 非常抱歉 :sad:

**Comment by jiancheng2018** [comment]
关键我不会啊，大神等你有机会的时候，再发一个上来吧！

**Comment by wakasann** [comment]
好的，等我的android 开发环境配置好，我才时间能试编译一个新的apk出来(今天不会有)， 如果需要使用，可以暂时先用着 [web版](https://www.wakasann.com/kuaishouv/) 的，原理和功能是一样的 :smile:

**Comment by jiancheng2018** [comment]
好的，谢谢您的回复，期待你的软件

**Comment by jiancheng2018** [comment]
大神可不可以加个微信？daijiancheng168

**Comment by wakasann** [comment]
编译了新的apk 1.0.2-beta,可以安装试试 :smile: 
ps: wx添加成功，如果可以，请删除带有wx账号那条的回复记录哟 💁‍♂
